language: node_js
node_js:
  - "12"
cache: yarn

install:
  - yarn install
  - yarn global add firebase-tools

script:
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: master
